export type Sura = {
	slug: string;
	id: string;
	name: string;
	nameAl: string;
	arabicName: string;
	place: string;
	ayahs: number;
	words: number;
	chars: number;
	desc?: string;
	order: number;
	revealOrder: number;
	juz?: number;
};

export const surahs = [
	{
		id: '001',
		slug: 'al-fatiha',
		name: 'Al-Fātiha',
		nameAl: 'Hapja',
		arabicName: 'الفاتحة',
		place: 'Mekë',
		ayahs: 7,
		words: 74,
		chars: 314,
		order: 1,
		revealOrder: 5,
	},
	{
		id: '002',
		slug: 'al-baqara',
		name: 'Al-Baqara',
		nameAl: 'Lopa',
		arabicName: 'البقرة',
		place: 'Medinë',
		ayahs: 286,
		words: 12316,
		chars: 52639,
		order: 2,
		revealOrder: 87,
	},
	{
		id: '003',
		slug: 'aal-imran',
		name: 'Āl-`Imrān',
		nameAl: 'Imrani (babai i Musës a.s.)',
		arabicName: 'آل عمران',
		place: 'Medinë',
		ayahs: 200,
		words: 7080,
		chars: 30276,
		order: 3,
		revealOrder: 89,
	},
	{
		id: '004',
		slug: 'an-nisa',
		name: "An-Nisā'",
		nameAl: 'Gruaja',
		arabicName: 'النّساء',
		place: 'Medinë',
		ayahs: 176,
		words: 7347,
		chars: 31845,
		order: 4,
		revealOrder: 92,
	},
	{
		id: '005',
		slug: 'al-maida',
		name: "Al-Mā'ida",
		nameAl: 'Tryeza',
		arabicName: 'المآئدة',
		place: 'Medinë',
		ayahs: 120,
		words: 5598,
		chars: 23932,
		order: 5,
		revealOrder: 112,
	},
	{
		id: '006',
		slug: 'al-anam',
		name: 'Al-An`ām',
		nameAl: 'Bagëtia',
		arabicName: 'الانعام',
		place: 'Mekë',
		ayahs: 165,
		words: 6226,
		chars: 26109,
		order: 6,
		revealOrder: 55,
	},
	{
		id: '007',
		slug: 'al-araf',
		name: 'Al-A`rāf',
		nameAl: 'Lartësitë',
		arabicName: 'الأعراف',
		place: 'Mekë',
		ayahs: 206,
		words: 6796,
		chars: 28550,
		order: 7,
		revealOrder: 39,
	},
	{
		id: '008',
		slug: 'al-anfal',
		name: "Al-'Anfāl",
		nameAl: 'Plaëkat e luftës',
		arabicName: 'الأنفال',
		place: 'Medinë',
		ayahs: 75,
		words: 2525,
		chars: 10834,
		order: 8,
		revealOrder: 88,
	},
	{
		id: '009',
		slug: 'at-tawba',
		name: 'At-Tawba',
		nameAl: 'Pendimi',
		arabicName: 'التوبة',
		place: 'Medinë',
		ayahs: 129,
		words: 5169,
		chars: 22679,
		order: 9,
		revealOrder: 113,
	},
	{
		id: '010',
		slug: 'yunus',
		name: 'Yūnus',
		nameAl: 'Junusi (I dërguar)',
		arabicName: 'يونس',
		place: 'Mekë',
		ayahs: 109,
		words: 3588,
		chars: 14947,
		order: 10,
		revealOrder: 51,
	},
	{
		id: '011',
		slug: 'hud',
		name: 'Hūd',
		nameAl: 'Hudi (I dërguar)',
		arabicName: 'هود',
		place: 'Mekë',
		ayahs: 123,
		words: 3930,
		chars: 16168,
		order: 11,
		revealOrder: 52,
	},
	{
		id: '012',
		slug: 'yusuf',
		name: 'Yūsuf',
		nameAl: 'Jusuf (I dërguar)',
		arabicName: 'يوسف',
		place: 'Mekë',
		ayahs: 111,
		words: 3566,
		chars: 14512,
		order: 12,
		revealOrder: 53,
	},
	{
		id: '013',
		slug: 'ar-rad',
		name: 'Ar-Ra`d',
		nameAl: 'Bubullima',
		arabicName: 'الرّعد',
		place: 'Medinë',
		ayahs: 43,
		words: 1701,
		chars: 7360,
		order: 13,
		revealOrder: 96,
	},
	{
		id: '014',
		slug: 'ibrahim',
		name: 'Ibrāhīm',
		nameAl: 'Ibrahimi (I dërguar)',
		arabicName: 'إبراهيم',
		place: 'Medinë',
		ayahs: 52,
		words: 1649,
		chars: 7050,
		order: 14,
		revealOrder: 72,
	},
	{
		id: '015',
		slug: 'al-hijr',
		name: 'Al-Hijr',
		nameAl: 'Hixhr',
		arabicName: 'الحجر',
		place: 'Mekë',
		ayahs: 99,
		words: 1389,
		chars: 5896,
		order: 15,
		revealOrder: 54,
	},
	{
		id: '016',
		slug: 'an-nahl',
		name: 'An-Nahl',
		nameAl: 'Bleta',
		arabicName: 'النّحل',
		place: 'Mekë',
		ayahs: 128,
		words: 3757,
		chars: 15908,
		order: 16,
		revealOrder: 70,
	},
	{
		id: '017',
		slug: 'al-isra',
		name: "Al-Isrā'",
		nameAl: 'Israja dhe Miraxhi',
		arabicName: 'الإسرا',
		place: 'Mekë',
		ayahs: 111,
		words: 3223,
		chars: 13549,
		order: 17,
		revealOrder: 50,
	},
	{
		id: '018',
		slug: 'al-kahf',
		name: 'Al-Kahf',
		nameAl: 'Shpella',
		arabicName: 'الكهف',
		place: 'Mekë',
		ayahs: 110,
		words: 3350,
		chars: 13823,
		order: 18,
		revealOrder: 69,
	},
	{
		id: '019',
		slug: 'maryam',
		name: 'Maryam',
		nameAl: 'Merjeme (nëna e Isës a.s.)',
		arabicName: 'مريم',
		place: 'Mekë',
		ayahs: 98,
		words: 2036,
		chars: 8188,
		order: 19,
		revealOrder: 44,
	},
	{
		id: '020',
		slug: 'ta-ha',
		name: 'Tā-Hā',
		nameAl: 'Ta-Ha',
		arabicName: 'طه',
		place: 'Mekë',
		ayahs: 135,
		words: 2830,
		chars: 11608,
		order: 20,
		revealOrder: 45,
	},
	{
		id: '021',
		slug: 'al-anbiya',
		name: 'Al-Anbiyā',
		nameAl: 'Pejgamberat',
		arabicName: 'الأنبياء',
		place: 'Mekë',
		ayahs: 112,
		words: 1903,
		chars: 7743,
		order: 21,
		revealOrder: 73,
	},
	{
		id: '022',
		slug: 'al-hajj',
		name: 'Al-Ḥajj',
		nameAl: 'Haxh',
		arabicName: 'الحج',
		place: 'Medinë',
		ayahs: 78,
		words: 1279,
		chars: 5104,
		order: 22,
		revealOrder: 103,
	},
	{
		id: '023',
		slug: 'al-muminun',
		name: 'Al-Mu’minūn',
		nameAl: 'Besimtarët',
		arabicName: 'المؤمنون',
		place: 'Mekë',
		ayahs: 118,
		words: 1840,
		chars: 7376,
		order: 23,
		revealOrder: 74,
	},
	{
		id: '024',
		slug: 'an-nur',
		name: 'An-Nūr',
		nameAl: 'Drita',
		arabicName: 'النور',
		place: 'Medinë',
		ayahs: 64,
		words: 1317,
		chars: 5596,
		order: 24,
		revealOrder: 102,
	},
	{
		id: '025',
		slug: 'al-furqan',
		name: 'Al-Furqān',
		nameAl: 'Standardi',
		arabicName: 'الفرقان',
		place: 'Mekë',
		ayahs: 77,
		words: 898,
		chars: 3902,
		order: 25,
		revealOrder: 42,
	},
	{
		id: '026',
		slug: 'ash-shuara',
		name: 'Ash-Shu‘arā’',
		nameAl: 'Poetët',
		arabicName: 'الشعراء',
		place: 'Mekë',
		ayahs: 227,
		words: 1324,
		chars: 5582,
		order: 26,
		revealOrder: 47,
	},
	{
		id: '027',
		slug: 'an-naml',
		name: 'An-Naml',
		nameAl: 'Milingonat',
		arabicName: 'النمل',
		place: 'Mekë',
		ayahs: 93,
		words: 1236,
		chars: 4960,
		order: 27,
		revealOrder: 48,
	},
	{
		id: '028',
		slug: 'al-qasas',
		name: 'Al-Qaṣaṣ',
		nameAl: 'Tregimet',
		arabicName: 'القصص',
		place: 'Mekë',
		ayahs: 88,
		words: 1433,
		chars: 5804,
		order: 28,
		revealOrder: 49,
	},
	{
		id: '029',
		slug: 'al-ankabut',
		name: 'Al-‘Ankabūt',
		nameAl: 'Merimanga',
		arabicName: 'العنكبوت',
		place: 'Mekë',
		ayahs: 69,
		words: 982,
		chars: 4192,
		order: 29,
		revealOrder: 85,
	},
	{
		id: '030',
		slug: 'ar-rum',
		name: 'Ar-Rūm',
		nameAl: 'Romakët',
		arabicName: 'الروم',
		place: 'Mekë',
		ayahs: 60,
		words: 818,
		chars: 3460,
		order: 30,
		revealOrder: 84,
	},
	{
		id: '031',
		slug: 'luqman',
		name: 'Luqmān',
		nameAl: 'Lukmani',
		arabicName: 'لقمان',
		place: 'Mekë',
		ayahs: 34,
		words: 550,
		chars: 2195,
		order: 31,
		revealOrder: 57,
	},
	{
		id: '032',
		slug: 'as-sajda',
		name: 'As-Sajdah',
		nameAl: 'Sexhdeja',
		arabicName: 'السجدة',
		place: 'Mekë',
		ayahs: 30,
		words: 375,
		chars: 1523,
		order: 32,
		revealOrder: 75,
	},
	{
		id: '033',
		slug: 'al-ahzab',
		name: 'Al-Aḥzāb',
		nameAl: 'Aleancat',
		arabicName: 'الأحزاب',
		place: 'Medinë',
		ayahs: 73,
		words: 1303,
		chars: 5385,
		order: 33,
		revealOrder: 90,
	},
	{
		id: '034',
		slug: 'saba',
		name: 'Saba’',
		nameAl: "Sebe'ë",
		arabicName: 'سبإ',
		place: 'Mekë',
		ayahs: 54,
		words: 884,
		chars: 3618,
		order: 34,
		revealOrder: 58,
	},
	{
		id: '035',
		slug: 'fatir',
		name: 'Fāṭir',
		nameAl: 'Krijuesi',
		arabicName: 'فاطر',
		place: 'Mekë',
		ayahs: 45,
		words: 780,
		chars: 3223,
		order: 35,
		revealOrder: 43,
	},
	{
		id: '036',
		slug: 'ya-sin',
		name: 'Yā-Sīn',
		nameAl: 'Jasin',
		arabicName: 'يس',
		place: 'Mekë',
		ayahs: 83,
		words: 807,
		chars: 3028,
		order: 36,
		revealOrder: 41,
	},
	{
		id: '037',
		slug: 'as-saffat',
		name: 'Aṣ-Ṣāffāt',
		nameAl: 'Të rreshtuarit',
		arabicName: 'الصافات',
		place: 'Mekë',
		ayahs: 182,
		words: 865,
		chars: 3505,
		order: 37,
		revealOrder: 56,
	},
	{
		id: '038',
		slug: 'sad',
		name: 'Ṣād',
		nameAl: 'Sad',
		arabicName: 'ص',
		place: 'Mekë',
		ayahs: 88,
		words: 733,
		chars: 2964,
		order: 38,
		revealOrder: 38,
	},
	{
		id: '039',
		slug: 'az-zumar',
		name: 'Az-Zumar',
		nameAl: 'Turmat',
		arabicName: 'الزمر',
		place: 'Mekë',
		ayahs: 75,
		words: 1186,
		chars: 4827,
		order: 39,
		revealOrder: 59,
	},
	{
		id: '040',
		slug: 'ghafir',
		name: 'Ghāfir',
		nameAl: 'Falësi',
		arabicName: 'غافر',
		place: 'Mekë',
		ayahs: 85,
		words: 1228,
		chars: 4968,
		order: 40,
		revealOrder: 60,
	},
	{
		id: '041',
		slug: 'fussilat',
		name: 'Fussilat',
		nameAl: 'Të shpjeguara qartë',
		arabicName: 'فصّلت',
		place: 'Mekë',
		ayahs: 54,
		words: 1648,
		chars: 6929,
		order: 41,
		revealOrder: 61,
	},
	{
		id: '042',
		slug: 'ash-shura',
		name: 'Ash-Shūrā',
		nameAl: 'Këshillimi',
		arabicName: 'الشّورى',
		place: 'Mekë',
		ayahs: 53,
		words: 1682,
		chars: 7227,
		order: 42,
		revealOrder: 62,
	},
	{
		id: '043',
		slug: 'az-zukhruf',
		name: 'Az-Zukhruf',
		nameAl: 'Stolitë',
		arabicName: 'الزّخرف',
		place: 'Mekë',
		ayahs: 89,
		words: 1785,
		chars: 7486,
		order: 43,
		revealOrder: 63,
	},
	{
		id: '044',
		slug: 'ad-dukhan',
		name: 'Ad-Dukhān',
		nameAl: 'Tymi',
		arabicName: 'الدّخان',
		place: 'Mekë',
		ayahs: 59,
		words: 710,
		chars: 3023,
		order: 44,
		revealOrder: 64,
	},
	{
		id: '045',
		slug: 'al-jathiya',
		name: 'Al-Jāthiya',
		nameAl: 'Të gjunjëzuarit',
		arabicName: 'الجاثية',
		place: 'Mekë',
		ayahs: 37,
		words: 999,
		chars: 4167,
		order: 45,
		revealOrder: 65,
	},
	{
		id: '046',
		slug: 'al-ahqaf',
		name: 'Al-Ahqāf',
		nameAl: 'Al-Ahqaf',
		arabicName: 'الأحقاف',
		place: 'Mekë',
		ayahs: 35,
		words: 1311,
		chars: 5561,
		order: 46,
		revealOrder: 66,
	},
	{
		id: '047',
		slug: 'muhammad',
		name: 'Muhammad',
		nameAl: 'Muhammad ﷺ',
		arabicName: 'محمّد',
		place: 'Medinë',
		ayahs: 38,
		words: 1099,
		chars: 4853,
		order: 47,
		revealOrder: 95,
	},
	{
		id: '048',
		slug: 'al-fath',
		name: 'Al-Fath',
		nameAl: 'Fitorja',
		arabicName: 'الفتح',
		place: 'Medinë',
		ayahs: 29,
		words: 1169,
		chars: 5157,
		order: 48,
		revealOrder: 111,
	},
	{
		id: '049',
		slug: 'al-hujurat',
		name: 'Al-Hujurāt',
		nameAl: 'Dhomat',
		arabicName: 'الحجرات',
		place: 'Medinë',
		ayahs: 18,
		words: 663,
		chars: 2889,
		order: 49,
		revealOrder: 106,
	},
	{
		id: '050',
		slug: 'qaf',
		name: 'Qāf',
		nameAl: 'Kaf',
		arabicName: 'ق',
		place: 'Mekë',
		ayahs: 45,
		words: 762,
		chars: 3150,
		order: 50,
		revealOrder: 34,
	},
	{
		id: '051',
		slug: 'adh-dhariyat',
		name: 'Adh-Dhāriyāt',
		nameAl: 'Erërat ',
		arabicName: 'الذّاريات',
		place: 'Mekë',
		ayahs: 60,
		words: 753,
		chars: 3182,
		order: 51,
		revealOrder: 67,
	},
	{
		id: '052',
		slug: 'at-tur',
		name: 'At-Tūr',
		nameAl: 'Mali Tur',
		arabicName: 'الطّور',
		place: 'Medinë',
		ayahs: 49,
		words: 680,
		chars: 2852,
		order: 52,
		revealOrder: 76,
	},
	{
		id: '053',
		slug: 'an-najm',
		name: 'An-Najm',
		nameAl: 'Ylli',
		arabicName: 'النّجْم',
		place: 'Mekë',
		ayahs: 62,
		words: 738,
		chars: 3072,
		order: 53,
		revealOrder: 23,
	},
	{
		id: '054',
		slug: 'al-qamar',
		name: 'Al-Qamar',
		nameAl: 'Hëna',
		arabicName: 'القمر',
		place: 'Mekë',
		ayahs: 55,
		words: 723,
		chars: 3155,
		order: 54,
		revealOrder: 37,
	},
	{
		id: '055',
		slug: 'ar-rahman',
		name: 'Ar-Rahmān',
		nameAl: 'Mëshiruesi',
		arabicName: 'الرّحْمن',
		place: 'Medinë',
		ayahs: 78,
		words: 815,
		chars: 3278,
		order: 55,
		revealOrder: 97,
	},
	{
		id: '056',
		slug: 'waqiah',
		name: 'Al-Wāqiah',
		nameAl: 'Ndodhia',
		arabicName: 'الواقعة',
		place: 'Mekë',
		ayahs: 96,
		words: 849,
		chars: 3538,
		order: 56,
		revealOrder: 46,
	},
	{
		id: '057',
		slug: 'hadid',
		name: 'Al-Hadīd',
		nameAl: 'Hekuri',
		arabicName: 'الحديد',
		place: 'Medinë',
		ayahs: 29,
		words: 1188,
		chars: 5139,
		order: 57,
		revealOrder: 94,
	},
	{
		id: '058',
		slug: 'mujadila',
		name: 'Al-Mujādala',
		nameAl: 'Gruaja që debaton',
		arabicName: 'المجادلة',
		place: 'Medinë',
		ayahs: 22,
		words: 920,
		chars: 4111,
		order: 58,
		revealOrder: 105,
	},
	{
		id: '059',
		slug: 'hashr',
		name: 'Al-Hashr',
		nameAl: 'Tubimi',
		arabicName: 'الحشْر',
		place: 'Medinë',
		ayahs: 24,
		words: 897,
		chars: 3971,
		order: 59,
		revealOrder: 101,
	},
	{
		id: '060',
		slug: 'mumtahana',
		name: 'Al-Mumtahana',
		nameAl: 'Gruaja e Sprovuar',
		arabicName: 'الممتحنة',
		place: 'Medinë',
		ayahs: 13,
		words: 715,
		chars: 3129,
		order: 60,
		revealOrder: 91,
	},
	{
		id: '061',
		slug: 'saff',
		name: 'As-Saff',
		nameAl: 'Rreshtat e besimtarëve',
		arabicName: 'الصّفّ',
		place: 'Medinë',
		ayahs: 14,
		words: 425,
		chars: 1828,
		order: 61,
		revealOrder: 109,
	},
	{
		id: '062',
		slug: 'jumua',
		name: 'Al-Jumua',
		nameAl: 'Xhuma',
		arabicName: 'الجمعة',
		place: 'Medinë',
		ayahs: 11,
		words: 341,
		chars: 1406,
		order: 62,
		revealOrder: 110,
	},
	{
		id: '063',
		slug: 'munafiqun',
		name: 'Al-Munāfiqūn',
		nameAl: 'Hipokritët',
		arabicName: 'المنافقون',
		place: 'Medinë',
		ayahs: 11,
		words: 367,
		chars: 1558,
		order: 63,
		revealOrder: 104,
	},
	{
		id: '064',
		slug: 'taghabun',
		name: 'At-Taghābun',
		nameAl: 'Zhgënjim i ndërsjelltë',
		arabicName: 'التّغابن',
		place: 'Medinë',
		ayahs: 18,
		words: 503,
		chars: 2182,
		order: 64,
		revealOrder: 108,
	},
	{
		id: '065',
		slug: 'talaq',
		name: 'At-Talāq',
		nameAl: 'Divorci',
		arabicName: 'الطّلاق',
		place: 'Medinë',
		ayahs: 12,
		words: 562,
		chars: 2511,
		order: 65,
		revealOrder: 99,
	},
	{
		id: '066',
		slug: 'tahrim',
		name: 'At-Tahrīm',
		nameAl: 'Ndalimi',
		arabicName: 'التّحريم',
		place: 'Medinë',
		ayahs: 12,
		words: 478,
		chars: 2115,
		order: 66,
		revealOrder: 107,
	},
	{
		id: '067',
		slug: 'mulk',
		name: 'Al-Mulk',
		nameAl: 'Sovraniteti',
		arabicName: 'الملك',
		place: 'Medinë',
		ayahs: 30,
		words: 659,
		chars: 2707,
		order: 67,
		revealOrder: 77,
	},
	{
		id: '068',
		slug: 'qalam',
		name: 'Al-Qalam',
		nameAl: 'Lapsi',
		arabicName: 'القلم',
		place: 'Mekë',
		ayahs: 52,
		words: 650,
		chars: 2760,
		order: 68,
		revealOrder: 2,
	},
	{
		id: '069',
		slug: 'haqqah',
		name: 'Al-Hāqqah',
		nameAl: 'E Pashmangshmja',
		arabicName: 'الحآقّة',
		place: 'Medinë',
		ayahs: 52,
		words: 575,
		chars: 2318,
		order: 69,
		revealOrder: 78,
	},
	{
		id: '070',
		slug: 'maarij',
		name: 'Al-Maārij',
		nameAl: 'Shkallët e Larta',
		arabicName: 'المعارج',
		place: 'Medinë',
		ayahs: 44,
		words: 448,
		chars: 1945,
		order: 70,
		revealOrder: 79,
	},
	{
		id: '071',
		slug: 'nuh-a.s',
		name: 'Nūh',
		nameAl: 'Nuh a.s',
		arabicName: 'نوح',
		place: 'Mekë',
		ayahs: 28,
		words: 227,
		chars: 965,
		order: 71,
		revealOrder: 71,
	},
	{
		id: '072',
		slug: 'jinn',
		name: 'Al-Jinn',
		nameAl: 'Xhindët',
		arabicName: 'الجن',
		place: 'Mekë',
		ayahs: 28,
		words: 285,
		chars: 1103,
		order: 72,
		revealOrder: 40,
	},
	{
		id: '073',
		slug: 'al-muzzammil',
		name: 'Al-Muzzammil',
		nameAl: 'I Mbështjelluri',
		arabicName: 'المزمل',
		place: 'Mekë',
		ayahs: 20,
		words: 244,
		chars: 1003,
		order: 73,
		revealOrder: 3,
	},
	{
		id: '074',
		slug: 'al-muddathir',
		name: 'Al-Muddathir',
		nameAl: 'I Mbuluari',
		arabicName: 'المدثر',
		place: 'Mekë',
		ayahs: 56,
		words: 257,
		chars: 1036,
		order: 74,
		revealOrder: 4,
	},
	{
		id: '075',
		slug: 'al-qiyamah',
		name: 'Al-Qiyāmah',
		nameAl: 'Ringjallja',
		arabicName: 'القيامة',
		place: 'Mekë',
		ayahs: 40,
		words: 164,
		chars: 676,
		order: 75,
		revealOrder: 31,
	},
	{
		id: '076',
		slug: 'al-insan',
		name: 'Al-Insān',
		nameAl: 'Njeriu',
		arabicName: 'الإنسان',
		place: 'Medinë',
		ayahs: 31,
		words: 241,
		chars: 1102,
		order: 76,
		revealOrder: 98,
	},
	{
		id: '077',
		slug: 'al-mursalat',
		name: 'Al-Mursalāt',
		nameAl: 'Engjëjt e Dërguar',
		arabicName: 'المرسلات',
		place: 'Mekë',
		ayahs: 50,
		words: 181,
		chars: 774,
		order: 77,
		revealOrder: 33,
	},
	{
		id: '078',
		slug: 'naba',
		name: 'An-Naba',
		nameAl: 'Lajmi i Madh',
		arabicName: 'النبأ',
		place: 'Mekë',
		ayahs: 40,
		words: 174,
		chars: 762,
		order: 78,
		revealOrder: 80,
	},
	{
		id: '079',
		slug: 'an-naziat',
		name: 'An-Nāziʻāt',
		nameAl: 'Ata që tërheqin',
		arabicName: 'النازعات',
		place: 'Mekë',
		ayahs: 46,
		words: 179,
		chars: 769,
		order: 79,
		revealOrder: 81,
	},
	{
		id: '080',
		slug: 'abasa',
		name: 'Abasa',
		nameAl: 'Ai U Vrenjt',
		arabicName: 'عبس',
		place: 'Mekë',
		ayahs: 42,
		words: 133,
		chars: 553,
		order: 80,
		revealOrder: 24,
	},
	{
		id: '081',
		slug: 'at-takwir',
		name: 'At-Takwīr',
		nameAl: 'Rrotullimi (Errësimi)',
		arabicName: 'التكوير',
		place: 'Mekë',
		ayahs: 29,
		words: 104,
		chars: 432,
		order: 81,
		revealOrder: 7,
	},
	{
		id: '082',
		slug: 'al-infitar',
		name: 'Al-Infitār',
		nameAl: 'Çarja e qiellit',
		arabicName: 'الإنفطار',
		place: 'Mekë',
		ayahs: 19,
		words: 81,
		chars: 329,
		order: 82,
		revealOrder: 82,
	},
	{
		id: '083',
		slug: 'al-mutaffifin',
		name: 'Al-Mutaffifīn',
		nameAl: 'Mashtruesit në peshore',
		arabicName: 'المطففين',
		place: 'Mekë',
		ayahs: 36,
		words: 169,
		chars: 738,
		order: 83,
		revealOrder: 86,
	},
	{
		id: '084',
		slug: 'al-inshiqaq',
		name: 'Al-Inshiqāq',
		nameAl: 'Bindja',
		arabicName: 'الإنشقاق',
		place: 'Mekë',
		ayahs: 25,
		words: 105,
		chars: 425,
		order: 84,
		revealOrder: 83,
	},
	{
		id: '085',
		slug: 'al-buruj',
		name: 'Al-Burūj',
		nameAl: 'Yjësitë',
		arabicName: 'البروج',
		place: 'Mekë',
		ayahs: 22,
		words: 92,
		chars: 372,
		order: 85,
		revealOrder: 27,
	},
	{
		id: '086',
		slug: 'at-tariq',
		name: 'At-Tāriq',
		nameAl: 'Ylli i Mëngjesit',
		arabicName: 'الطارق',
		place: 'Mekë',
		ayahs: 17,
		words: 61,
		chars: 250,
		order: 86,
		revealOrder: 36,
	},
	{
		id: '087',
		slug: 'al-ala',
		name: 'Al-Aʻlā',
		nameAl: 'Më i Larti',
		arabicName: 'الأعلى',
		place: 'Mekë',
		ayahs: 19,
		words: 72,
		chars: 296,
		order: 87,
		revealOrder: 8,
	},
	{
		id: '088',
		slug: 'al-ghashiyah',
		name: 'Al-Ghāshiyah',
		nameAl: 'Ngjarja Pushtuese',
		arabicName: 'الغاشية',
		place: 'Mekë',
		ayahs: 26,
		words: 92,
		chars: 368,
		order: 88,
		revealOrder: 68,
	},
	{
		id: '089',
		slug: 'al-fajr',
		name: 'Al-Fajr',
		nameAl: 'Agimi',
		arabicName: 'الفجر',
		place: 'Mekë',
		ayahs: 30,
		words: 139,
		chars: 584,
		order: 89,
		revealOrder: 10,
	},
	{
		id: '090',
		slug: 'al-balad',
		name: 'Al-Balad',
		nameAl: 'Qyteti',
		arabicName: 'البلد',
		place: 'Mekë',
		ayahs: 20,
		words: 82,
		chars: 337,
		order: 90,
		revealOrder: 35,
	},
	{
		id: '091',
		slug: 'ash-shams',
		name: 'Ash-Shams',
		nameAl: 'Dielli',
		arabicName: 'الشمس',
		place: 'Mekë',
		ayahs: 15,
		words: 54,
		chars: 245,
		order: 91,
		revealOrder: 26,
	},
	{
		id: '092',
		slug: 'al-lail',
		name: 'Al-Lail',
		nameAl: 'Nata',
		arabicName: 'الليل',
		place: 'Mekë',
		ayahs: 21,
		words: 71,
		chars: 295,
		order: 92,
		revealOrder: 9,
	},
	{
		id: '093',
		slug: 'ad-duha',
		name: 'Ad-Duḥā',
		nameAl: 'Mëngjesi',
		arabicName: 'الضحى',
		place: 'Mekë',
		ayahs: 11,
		words: 40,
		chars: 165,
		order: 93,
		revealOrder: 11,
	},
	{
		id: '094',
		slug: 'ash-sharh',
		name: 'Ash-Sharḥ',
		nameAl: 'Zgjerimi i Kraharorit',
		arabicName: 'الشرح',
		place: 'Mekë',
		ayahs: 8,
		words: 30,
		chars: 120,
		order: 94,
		revealOrder: 12,
	},
	{
		id: '095',
		slug: 'at-tin',
		name: 'At-Tīn',
		nameAl: 'Fiku',
		arabicName: 'التين',
		place: 'Mekë',
		ayahs: 8,
		words: 34,
		chars: 144,
		order: 95,
		revealOrder: 28,
	},
	{
		id: '096',
		slug: 'al-alaq',
		name: 'Al-ʻAlaq',
		nameAl: 'Mpiksja',
		arabicName: 'العلق',
		place: 'Mekë',
		ayahs: 19,
		words: 92,
		chars: 380,
		order: 96,
		revealOrder: 1,
	},
	{
		id: '097',
		slug: 'al-qadr',
		name: 'Al-Qadr',
		nameAl: 'Natë e Caktimit/Fuqishme',
		arabicName: 'القدر',
		place: 'Mekë',
		ayahs: 5,
		words: 30,
		chars: 114,
		order: 97,
		revealOrder: 25,
	},
	{
		id: '098',
		slug: 'al-bayyinah',
		name: 'Al-Bayyinah',
		nameAl: 'Prova e Qartë',
		arabicName: 'البينة',
		place: 'Medinë',
		ayahs: 8,
		words: 102,
		chars: 427,
		order: 98,
		revealOrder: 100,
	},
	{
		id: '099',
		slug: 'az-zalzalah',
		name: 'Az-Zalzalah',
		nameAl: 'Tërmeti',
		arabicName: 'الزلزلة',
		place: 'Medinë',
		ayahs: 8,
		words: 36,
		chars: 158,
		order: 99,
		revealOrder: 93,
	},
	{
		id: '100',
		slug: 'al-adiyat',
		name: 'Al-ʻĀdiyāt',
		nameAl: 'Kuajt',
		arabicName: 'العاديات',
		place: 'Mekë',
		ayahs: 11,
		words: 40,
		chars: 176,
		order: 100,
		revealOrder: 14,
	},
	{
		id: '101',
		slug: 'qariah',
		name: 'Al-Qāriʻah',
		nameAl: 'Krismat',
		arabicName: 'القارعة',
		place: 'Mekë',
		ayahs: 11,
		words: 36,
		chars: 158,
		order: 101,
		revealOrder: 30,
	},
	{
		id: '102',
		slug: 'at-takathur',
		name: 'At-Takāthur',
		nameAl: 'Garimi për më shumë-Krenaria',
		arabicName: 'التكاثر',
		place: 'Mekë',
		ayahs: 8,
		words: 28,
		chars: 120,
		order: 102,
		revealOrder: 16,
	},
	{
		id: '103',
		slug: 'al-asr',
		name: 'Al-ʻAsr',
		nameAl: 'Koha',
		arabicName: 'العصر',
		place: 'Mekë',
		ayahs: 3,
		words: 14,
		chars: 68,
		order: 103,
		revealOrder: 13,
	},
	{
		id: '104',
		slug: 'al-humazah',
		name: 'Al-Humazah',
		nameAl: 'Përqeshësi',
		arabicName: 'الهمزة',
		place: 'Mekë',
		ayahs: 9,
		words: 33,
		chars: 133,
		order: 104,
		revealOrder: 32,
	},
	{
		id: '105',
		slug: 'al-fil',
		name: 'Al-Fīl',
		nameAl: 'Elefanti',
		arabicName: 'الفيل',
		place: 'Mekë',
		ayahs: 5,
		words: 23,
		chars: 96,
		order: 105,
		revealOrder: 19,
	},
	{
		id: '106',
		slug: 'quraish',
		name: 'Quraish',
		nameAl: 'Kureishitët',
		arabicName: 'قريش',
		place: 'Mekë',
		ayahs: 4,
		words: 17,
		chars: 73,
		order: 106,
		revealOrder: 29,
	},
	{
		id: '107',
		slug: 'maun',
		name: 'Al-Māʻūn',
		nameAl: 'Ndihmesa e Vogël',
		arabicName: 'الماعون',
		place: 'Mekë',
		ayahs: 7,
		words: 25,
		chars: 114,
		order: 107,
		revealOrder: 17,
	},
	{
		id: '108',
		slug: 'al-kauthar',
		name: 'Al-Kawthar',
		nameAl: 'Begatia e Madhe',
		arabicName: 'الكوثر',
		place: 'Mekë',
		ayahs: 3,
		words: 10,
		chars: 42,
		order: 108,
		revealOrder: 15,
	},
	{
		id: '109',
		slug: 'al-kafiroon',
		name: 'Al-Kāfirūn',
		nameAl: 'Jobesimtarët',
		arabicName: 'الكافرون',
		place: 'Mekë',
		ayahs: 6,
		words: 27,
		chars: 94,
		order: 109,
		revealOrder: 18,
	},
	{
		id: '110',
		slug: 'nasr',
		name: 'An-Naṣr',
		nameAl: 'Ndihma e Allahut',
		arabicName: 'النصر',
		place: 'Medinë',
		ayahs: 3,
		words: 19,
		chars: 80,
		order: 110,
		revealOrder: 114,
	},
	{
		id: '111',
		slug: 'masad',
		name: 'Al-Masad',
		nameAl: 'Litarët',
		arabicName: 'المسد',
		place: 'Mekë',
		ayahs: 5,
		words: 23,
		chars: 94,
		order: 111,
		revealOrder: 6,
	},
	{
		id: '112',
		slug: 'al-ikhlas',
		name: 'Al-Ikhlāṣ',
		nameAl: 'Sinqeriteti i besimit',
		arabicName: 'الإخلاص',
		place: 'Mekë',
		ayahs: 4,
		words: 15,
		chars: 47,
		order: 112,
		revealOrder: 22,
	},
	{
		id: '113',
		slug: 'al-falaq',
		name: 'Al-Falaq',
		nameAl: 'Agimi i sabahut',
		arabicName: 'الفلق',
		place: 'Mekë',
		ayahs: 5,
		words: 23,
		chars: 79,
		order: 113,
		revealOrder: 20,
	},
	{
		id: '114',
		slug: 'an-nas',
		name: 'An-Nās',
		nameAl: 'Njerëzit',
		arabicName: 'الناس',
		place: 'Mekë',
		ayahs: 6,
		words: 20,
		chars: 80,
		order: 114,
		revealOrder: 21,
	},
];
